# kubetpl:syntax:$
---
apiVersion: v1
kind: Service
metadata:
  name: greetings
spec:
  selector:
    app: greetings
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings
  template:
    metadata:
      labels:
        app: greetings
    spec:
      containers:
      - name: greetings
        image: hello-spring:$IMAGE_TAG
        imagePullPolicy: $IMAGE_PULL_POLICY
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1"
