openapi: 3.1.0
info:
  title: Greetings API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /greetings:
    get:
      summary: Greets the user by name.
      parameters:
        - name: name
          in: query
          required: true
          description: The name of the person to greet.
          schema:
            type: string
      responses:
        '200':
          description: A greeting message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

